### ISSUE TITLE
Some Syntax Errors and Unknown Third-party Library "ImageFlow"

### ISSUE THREAD

**Issue by Mike-Solar** [hotpot-killer/Instruct-PG#2]
* It seems that "ImageFlow" is a third-party library, but I didn't find it on PyPi. So the folders in the project should not have the same name as the library.

In main.py:
* The module name is case-sensitive. It should be `instruct_pg` instead of `Instruct_pg`.

In requirements.txt:
* The pytorch, torchaudio, torchvision, triton and MarkupSafe should be downloaded from the PyTorch Official Website. The packages on PyPi is for CPU, not for GPU. Also some of the packages which name starts with `nvidia` is not on PyPi.

I've submitted a Pull request #1 for thesep problems.

***IMPORTANT***: This Pull request does ***NOT*** guaranteed to fix the problem because don't have the library "ImageFlow" so I can't test it.

**Comment by Mike-Solar** [comment]
I need to thanks to one of my friends. He found out these problems first.

**Comment by hotpot-killer** [comment]
> * It seems that "ImageFlow" is a third-party library, but I didn't find it on PyPi. So the folders in the project should not have the same name as the library.
> 
> In main.py:
> 
> * The module name is case-sensitive. It should be `instruct_pg` instead of `Instruct_pg`.
> 
> In requirements.txt:
> 
> * The pytorch, torchaudio, torchvision, triton and MarkupSafe should be downloaded from the PyTorch Official Website. The packages on PyPi is for CPU, not for GPU. Also some of the packages which name starts with `nvidia` is not on PyPi.
> 
> I've submitted a Pull request #1 for thesep problems.
> 
> _**IMPORTANT**_: This Pull request does _**NOT**_ guaranteed to fix the problem because don't have the library "ImageFlow" so I can't test it.

Thank you very much for your valuable feedback and for bringing these issues to my attention! I've taken note of the concerns you've raised regarding the "ImageFlow" library and the errors in the code. I truly appreciate the Pull Request #1 you've submitted. Although you've mentioned that without the "ImageFlow" library, you can't fully test, your suggestions are incredibly helpful for improving my code.

My code is indeed still a work in progress, and I will take your feedback very seriously. I plan to update the code in the near future to address these issues. I will pay special attention to the case sensitivity of module names and ensure that all dependencies are correctly installed, particularly the GPU versions of the PyTorch-related libraries.

Thank you again for your contributions and patience. I will work on these issues as soon as possible and keep the code updated. If you have any further questions or suggestions, please feel free to reach out.

Best regards,
hotpot-killer
